export enum EModalsNames {
  DocumentsPreviewModal = 'DocumentsPreviewModal',
  HelicopterOrderModal = 'HelicopterOrderModal',
  PassengerTransportationModal = 'PassengerTransportationModal',
  SendMessageModal = 'SendMessageModal',
  LogInModal = 'LogInModal',
  PasswordRecoveryModal = 'PasswordRecoveryModal',
  NewPasswordModal = 'NewPasswordModal',
  RegistrationModal = 'RegistrationModal',
  PasswordChangeModal = 'PasswordChangeModal',
  ProfileUpdateModal = 'ProfileUpdateModal',
  ProfileEditModal = 'ProfileEditModal',
  EmailChangeModal = 'EmailChangeModal',
  PhoneChangeModal = 'PhoneChangeModal',
  AddPassengerModal = 'AddPassengerModal',
  ChangePassengerModal = 'ChangePassengerModal',
  OrganizationUpdateModal = 'OrganizationUpdateModal',
  DeletePassengerModal = 'DeletePassengerModal',
  ScansSliderModal = 'ScansSliderModal',
}
